# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1205, 610)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_setup = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_setup.setGeometry(QtCore.QRect(985, 25, 205, 400))
        self.groupBox_setup.setObjectName("groupBox_setup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_setup.setLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("viticalLayout_2")
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.PB_IN_1 = QtWidgets.QPushButton()
        self.PB_IN_1.setObjectName("PB_IN_1")
        self.verticalLayout_2.addWidget(self.PB_IN_1)
        self.PB_IN_2 = QtWidgets.QPushButton()
        self.PB_IN_2.setObjectName("PB_IN_2")
        self.verticalLayout_2.addWidget(self.PB_IN_2)
        self.PB_IN_3 = QtWidgets.QPushButton()
        self.PB_IN_3.setObjectName("PB_IN_3")
        self.verticalLayout_2.addWidget(self.PB_IN_3)
        self.PB_IN_4 = QtWidgets.QPushButton()
        self.PB_IN_4.setObjectName("PB_IN_4")
        self.verticalLayout_2.addWidget(self.PB_IN_4)
        self.PB_IN_5 = QtWidgets.QPushButton()
        self.PB_IN_5.setObjectName("PB_IN_5")
        self.verticalLayout_2.addWidget(self.PB_IN_5)
        self.PB_IN_6 = QtWidgets.QPushButton()
        self.PB_IN_6.setObjectName("PB_IN_6")
        self.verticalLayout_2.addWidget(self.PB_IN_6)
        self.PB_IN_7 = QtWidgets.QPushButton()
        self.PB_IN_7.setObjectName("PB_IN_7")
        self.verticalLayout_2.addWidget(self.PB_IN_7)
        self.PB_IN_8 = QtWidgets.QPushButton()
        self.PB_IN_8.setObjectName("PB_IN_8")
        self.verticalLayout_2.addWidget(self.PB_IN_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("viticalLayout_3")
        self.PB_OUT_1 = QtWidgets.QPushButton()
        self.PB_OUT_1.setObjectName("PB_OUT_1")
        self.verticalLayout_3.addWidget(self.PB_OUT_1)
        self.PB_OUT_2 = QtWidgets.QPushButton()
        self.PB_OUT_2.setObjectName("PB_OUT_2")
        self.verticalLayout_3.addWidget(self.PB_OUT_2)
        self.PB_OUT_3 = QtWidgets.QPushButton()
        self.PB_OUT_3.setObjectName("PB_OUT_3")
        self.verticalLayout_3.addWidget(self.PB_OUT_3)
        self.PB_OUT_4 = QtWidgets.QPushButton()
        self.PB_OUT_4.setObjectName("PB_OUT_4")
        self.verticalLayout_3.addWidget(self.PB_OUT_4)
        self.PB_OUT_5 = QtWidgets.QPushButton()
        self.PB_OUT_5.setObjectName("PB_OUT_5")
        self.verticalLayout_3.addWidget(self.PB_OUT_5)
        self.PB_OUT_6 = QtWidgets.QPushButton()
        self.PB_OUT_6.setObjectName("PB_OUT_6")
        self.verticalLayout_3.addWidget(self.PB_OUT_6)
        self.PB_OUT_7 = QtWidgets.QPushButton()
        self.PB_OUT_7.setObjectName("PB_OUT_7")
        self.verticalLayout_3.addWidget(self.PB_OUT_7)
        self.PB_OUT_8 = QtWidgets.QPushButton()
        self.PB_OUT_8.setObjectName("PB_OUT_8")
        self.verticalLayout_3.addWidget(self.PB_OUT_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(15, 30, 960, 540))
        self.label_image.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.label_image.setText("")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.widget = QtWidgets.QWidget(self.centralwidget)######
        self.widget.setGeometry(QtCore.QRect(1010, 440, 145, 150)) #####
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_openVideo = QtWidgets.QPushButton(self.widget)
        self.pushButton_openVideo.setObjectName("pushButton_openVideo")
        self.verticalLayout.addWidget(self.pushButton_openVideo)
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Vehicle_counting_tracking_in_a_roundabout"))
        self.groupBox_setup.setTitle(_translate("mainWindow", "Lane set up"))
        self.PB_IN_1.setText(_translate("mainWindow", "IN_1"))
        self.PB_IN_2.setText(_translate("mainWindow", "IN_2"))
        self.PB_IN_3.setText(_translate("mainWindow", "IN_3"))
        self.PB_IN_4.setText(_translate("mainWindow", "IN_4"))
        self.PB_IN_5.setText(_translate("mainWindow", "IN_5"))
        self.PB_IN_6.setText(_translate("mainWindow", "IN_6"))
        self.PB_IN_7.setText(_translate("mainWindow", "IN_7"))
        self.PB_IN_8.setText(_translate("mainWindow", "IN_8"))
        self.PB_OUT_1.setText(_translate("mainWindow", "OUT_1"))
        self.PB_OUT_2.setText(_translate("mainWindow", "OUT_2"))
        self.PB_OUT_3.setText(_translate("mainWindow", "OUT_3"))
        self.PB_OUT_4.setText(_translate("mainWindow", "OUT_4"))
        self.PB_OUT_5.setText(_translate("mainWindow", "OUT_5"))
        self.PB_OUT_6.setText(_translate("mainWindow", "OUT_6"))
        self.PB_OUT_7.setText(_translate("mainWindow", "OUT_7"))
        self.PB_OUT_8.setText(_translate("mainWindow", "OUT_8"))
        self.pushButton_openVideo.setText(_translate("mainWindow", "Open Video"))
        self.pushButton_start.setText(_translate("mainWindow", "Start"))
